// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailcarTrip.Infrastructure.Context;

#nullable disable

namespace RailcarTrip.Infrastructure.Migrations
{
    [DbContext(typeof(RailcarDbContext))]
    [Migration("20260210210319_SeedDatabase")]
    partial class SeedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "W",
                            Description = "Released from origin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "A",
                            Description = "Arrived at location"
                        },
                        new
                        {
                            Id = 3,
                            Code = "D",
                            Description = "Departed from location"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Z",
                            Description = "Placed at Destination"
                        });
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vancouver",
                            Timezone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Victoria",
                            Timezone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kelowna",
                            Timezone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kamloops",
                            Timezone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Prince George",
                            Timezone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Calgary",
                            Timezone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Edmonton",
                            Timezone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lethbridge",
                            Timezone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Red Deer",
                            Timezone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fort McMurray",
                            Timezone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Regina",
                            Timezone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Saskatoon",
                            Timezone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Moose Jaw",
                            Timezone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Brandon",
                            Timezone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Winnipeg",
                            Timezone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Thunder Bay",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sault Ste. Marie",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sudbury",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 19,
                            Name = "North Bay",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Barrie",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Toronto",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Mississauga",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hamilton",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 24,
                            Name = "London",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kitchener",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Windsor",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 27,
                            Name = "St Catherines",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Oshawa",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Kingston",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Ottowa",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Gattineau",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Montreal",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Quebec City",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Sherbrooke",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Trois-RiviÃ¨res",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Saguenay",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Rimouski",
                            Timezone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Edmundston",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Fredericton",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Moncton",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Saint John",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Bathurst",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Charlottetown",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Summerside",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Sydney",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Turo",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 47,
                            Name = "New Glasgow",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dartmouth",
                            Timezone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Halifax",
                            Timezone = "Atlantic Standard Time"
                        });
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Railcar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Railcars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ACAR1234"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BCAR4321"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CCar1111"
                        });
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Railcar_Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("RailcarCode")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RailcarCode");

                    b.HasIndex("TripId");

                    b.ToTable("Railcar_Events");
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("OriginId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Railcar_Event", b =>
                {
                    b.HasOne("RailcarTrip.Domain.Entities.Event", "Event")
                        .WithMany("Railcar_Events")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailcarTrip.Domain.Entities.Location", "Location")
                        .WithMany("Railcar_Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailcarTrip.Domain.Entities.Railcar", "Railcar")
                        .WithMany("Events")
                        .HasForeignKey("RailcarCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailcarTrip.Domain.Entities.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Location");

                    b.Navigation("Railcar");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Trip", b =>
                {
                    b.HasOne("RailcarTrip.Domain.Entities.Location", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("RailcarTrip.Domain.Entities.Location", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Event", b =>
                {
                    b.Navigation("Railcar_Events");
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Location", b =>
                {
                    b.Navigation("Railcar_Events");
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Railcar", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RailcarTrip.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
